### ISSUE TITLE
Extension does not load when access to local storage is not allowed

### ISSUE THREAD

**Issue by oscarvantol** [oscarvantol/repo-board#8]
At this moment the favorites are stored in local storage, a user reported the following console error:
![image](https://user-images.githubusercontent.com/17926915/140740878-9fc06a73-6001-47b0-8385-fcf9a6783104.png)

options:
- provide a degraded experience without favs
- store the data as a user preference in AzDevOps

**Comment by marioese31** [comment]
You might want to check out the MDN recommendation on this topic:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage

**Comment by marioese31** [comment]
Resolved in PR #7

**Comment by oscarvantol** [comment]
Closing issue: For now removed favorites feature when local storage is not available.

thx @marioese31
